repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        require_serial: true
